name: deploy website
on:
  # 一応動確のために手動でGitHub Actionsを実行可能にする
  # その際の引数としてcheckout時のrefを渡している
  workflow_dispatch:
    inputs:
      ref:
        description: branch|tag|SHA to checkout
        default: 'main'
        required: true
  # 毎日10時にGitHub Actionsを実行(上記defaultブランチが参照される）
  schedule:
    - cron:  '0 1 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}
          
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Update
        run: 
          yarn add
          yarn build # 投稿内容を更新
      
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          # GitHub　Secretsで作成した値を参照
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-args: '--prod' # Optional
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
          working-directory: ./
